import Head from 'next/head'
import styles from "../styles/Layout.module.css"
import Link from 'next/link'

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Cascade GUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.headers}>
        <div className={styles.logoBox}>
          <div className={styles.diagonal}></div>
        </div>
      </header>
      <div className={styles.main}>
        <nav className={styles.sidebar}>
          <ul>
            <Link href="/">home</Link>
            <Link href="/application">application</Link>
            <Link href="/environments">environments</Link>
            <Link href="/services">services</Link>
          </ul>
        </nav>
        {children}
      </div>
      <footer>

      </footer>
    </div>
  )
}

export default Layout