import Head from 'next/head'
import styles from "../styles/Layout.module.css"
import Link from 'next/link'
import Image from 'next/image'

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Cascade GUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cascade.png" />
      </Head>

      <header className={styles.headers}>
        <div className={styles.logoContainer}>
          <div>
            <Image src="/images/logo.png" alt="cascade logo" width="456.4px" height="76.8px"/>
          </div>
        </div>
      </header>
      <div className={styles.main}>
        {children}
      </div>
      <footer>
        <div className={styles.logoBox}>
         <div className={styles.circleDiv}>
            {/* <Image src="/cascade.png" alt="cascade logo" width="100px" height="100px"/>` */}
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Layout