import Head from 'next/head'
import styles from "../styles/Layout.module.css"
import Link from 'next/link'
import Image from 'next/image'

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Cascade GUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.headers}>
        <div className={styles.logoBox}>
          <div className={styles.diagonal}></div>
        </div>
      </header>
      <div className={styles.main}>
        <nav className={styles.sidebar}>
          <ul>
            <li>
              <Link href="/">
                <div>
                  <Image src='/../public/images/home_blue.png' alt="home button" width="50px" height="50px" />
                  Home
                </div>
              </Link>
            </li>
            {/* <li>
              <Link href="/services">
                <div>
                  <Image src='/../public/images/fargate_blue.png' alt="services button" width="50px" height="50px" />
                  Services
                </div>
              </Link>
            </li> */}
          </ul>
        </nav>
        {children}
      </div>
      <footer>

      </footer>
    </div>
  )
}

export default Layout